version: "3.3"
services:
  postgres:  
    image: postgres:latest
    container_name: postgres
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    ports:
        -   "5000:5432"     
  
  binanceservice:
    container_name: binanceservice
    stdin_open: true
    image: binanceservice:latest
    environment: 
      DB_CONN: "Host=postgres;Port=5432;Database=BinanceProject;Username=postgres;Password=postgres"
    build:
      dockerfile: ./DockerfileBinanceService
<<<<<<< HEAD
    depends_on:
      - postgres
=======
>>>>>>> f09d0e873823d616052d03b8ed8ac34a4cab5105

  telegrambot:
    container_name: telegrambot
    stdin_open: true
<<<<<<< HEAD
    image: telegrambot
    environment:
      DB_CONN: "Host=postgres;Port=5432;Database=BinanceProject;Username=postgres;Password=postgres"
    build: 
      dockerfile: ./DockerfileTelegramBot
    depends_on:
      - postgres
=======
    image: telegrambot:latest
    environment:
      DB_CONN: "Host=postgres;Port=5432;Database=BinanceProject;Username=postgres;Password=postgres"
    build: 
      dockerfile: ./DockerfileTelegramBot
>>>>>>> f09d0e873823d616052d03b8ed8ac34a4cab5105
